-- Adds backend support tables/columns for sync freshness, lottery ownership,
-- and home/away CF split placeholders used by the app server.

create table if not exists public.sync_log (
  id bigint generated by default as identity primary key,
  sync_type text not null,
  synced_at timestamptz not null default timezone('utc'::text, now()),
  status text not null,
  error_msg text
);

create table if not exists public.pick_trades (
  id bigint generated by default as identity primary key,
  original_team text not null,
  current_owner text not null,
  round int not null,
  year int not null,
  conditions text
);

create table if not exists public.pick_protections (
  id bigint generated by default as identity primary key,
  team text not null,
  round int not null,
  year int not null,
  protection_type text not null,
  protected_threshold int
);

alter table public.player_seasons
  add column if not exists home_cf_pct float8,
  add column if not exists away_cf_pct float8;

alter table public.sync_log enable row level security;
alter table public.pick_trades enable row level security;
alter table public.pick_protections enable row level security;

drop policy if exists "sync_log_public_read" on public.sync_log;
create policy "sync_log_public_read"
on public.sync_log for select
using (true);

drop policy if exists "sync_log_authenticated_write" on public.sync_log;
create policy "sync_log_authenticated_write"
on public.sync_log for all
using (auth.role() in ('authenticated', 'service_role'))
with check (auth.role() in ('authenticated', 'service_role'));

drop policy if exists "pick_trades_public_read" on public.pick_trades;
create policy "pick_trades_public_read"
on public.pick_trades for select
using (true);

drop policy if exists "pick_trades_authenticated_write" on public.pick_trades;
create policy "pick_trades_authenticated_write"
on public.pick_trades for all
using (auth.role() in ('authenticated', 'service_role'))
with check (auth.role() in ('authenticated', 'service_role'));

drop policy if exists "pick_protections_public_read" on public.pick_protections;
create policy "pick_protections_public_read"
on public.pick_protections for select
using (true);

drop policy if exists "pick_protections_authenticated_write" on public.pick_protections;
create policy "pick_protections_authenticated_write"
on public.pick_protections for all
using (auth.role() in ('authenticated', 'service_role'))
with check (auth.role() in ('authenticated', 'service_role'));
